sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: '12'
install: yarn install
script: yarn test:coverage
after_script: npx codecov@3